# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/email_processor_db

# Gmail Configuration (IMAP)
mail.imap.host=imap.gmail.com
mail.imap.port=993
mail.imap.user=pruebas.token.quipux@gmail.com
# Usa aquí la contraseña de aplicación de 16 caracteres generada en Google
mail.imap.password=itugskiundkfrvfz
mail.imap.sender.filter=alejo.html@gmail.com

# SMTP Configuration for resending
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pruebas.token.quipux@gmail.com
# Usa aquí la misma contraseña de aplicación de 16 caracteres
spring.mail.password=itugskiundkfrvfz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# File Storage
file.upload-dir=C:/WorkSpace/Dei W/EmailProcessor/attachments

# Server Port
server.port=8082
server.servlet.context-path=/api
spring.application.name=email-processor

# AI Configuration
ai.openai.api-key=demo
ai.openai.model-name=gpt-4o
